version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project_db
    ports:
      - "5432:5432"
    volumes:
      - /absolute/path/to/directory-with-data:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d project_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
volumes:
  pg_data:
